import type { CaseDetail } from '@/types/case';
import { buildSubmissionPacket } from '@/lib/submissions/build-submission-packet';

export type ExportPacket = { caseId: string; readinessLabel: string; isDraft: boolean; sections: Array<{ title: string; rows: Array<[string, string]> }>; documents: string[] };

const verified = (value: string | undefined | null) => value?.trim() || 'Not verified';
function draftValue(detail: CaseDetail, key: string) { return detail.priorAuthDraft?.fields.find((f) => f.fieldKey === key && f.status === 'VERIFIED')?.displayValue || 'Not verified'; }

export function buildExportPacket(detail: CaseDetail): ExportPacket {
  const packet = buildSubmissionPacket(detail); const ready = packet.readyForPreparation;
  const value = (obj: Record<string, string>, key: string) => verified(obj[key]);
  return { caseId: detail.id, readinessLabel: ready ? 'READY FOR SPECIALIST SUBMISSION REVIEW' : 'DRAFT / NOT READY - UNRESOLVED REQUIREMENTS', isDraft: !ready, sections: [
    { title: 'PATIENT INFORMATION', rows: [['Patient name', detail.patientName], ['Date of birth', value(packet.patient, 'dateOfBirth')], ['Member / policy ID', value(packet.patient, 'memberPolicyId')]] },
    { title: 'PROVIDER INFORMATION', rows: [['Ordering provider', value(packet.provider, 'name')], ['NPI', value(packet.provider, 'npi')], ['Order date', value(packet.provider, 'orderDate')]] },
    { title: 'INSURANCE INFORMATION', rows: [['Payer', value(packet.insurance, 'payer')], ['Plan', value(packet.insurance, 'plan')]] },
    { title: 'REQUESTED EQUIPMENT', rows: [['Requested equipment', value(packet.request, 'equipment')], ['Equipment category', detail.equipmentCategory], ['HCPCS codes', value(packet.request, 'hcpcsCodes')], ['Accessories / components', value(packet.request, 'accessories')]] },
    { title: 'CLINICAL SUPPORT', rows: [['Diagnoses / codes', draftValue(detail, 'diagnosisTermsCodes')], ['Functional limitations', draftValue(detail, 'functionalLimitations')], ['Evaluation findings', draftValue(detail, 'evaluationFindings')], ['Reviewed medical rationale', draftValue(detail, 'medicalRationale')]] },
    { title: 'SUBMISSION INFORMATION', rows: [['Submission channel', verified(detail.submission?.submissionChannel || packet.policy?.submissionChannel)], ['Case ID', detail.id], ['Authorization status', detail.status], ['External reference', verified(detail.submission?.externalReferenceNumber)] ] },
  ], documents: packet.supportingDocuments };
}

export function renderPlainText(packet: ExportPacket) {
  return [`PRIOR AUTHORIZATION REQUEST`, `Case ${packet.caseId}`, packet.readinessLabel, '', ...packet.sections.flatMap((section) => [section.title, ...section.rows.map(([label, value]) => `${label}: ${value}`), '']), 'SUPPORTING DOCUMENTATION', ...packet.documents.map((document) => `- ${document}`), '', 'Synthetic demonstration data only. Human review required. No coverage or medical-necessity decision is made by the system.'].join('\n');
}

function escPdf(value: string) { return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/[\r\n]/g, ' '); }
function wrap(value: string, max: number) { const words = value.split(/\s+/); const lines: string[] = []; let line = ''; for (const word of words) { if ((line + ' ' + word).trim().length > max && line) { lines.push(line); line = word; } else line = (line ? line + ' ' : '') + word; } if (line) lines.push(line); return lines.length ? lines : ['']; }

export function renderPdf(packet: ExportPacket): Buffer {
  const pageW = 612; const margin = 54; const content: string[] = []; let page: string[] = []; let y = 0;
  const startPage = () => { page = []; y = 748; page.push('q 0.96 0.98 1 rg 0 0 612 792 re f Q'); };
  const text = (value: string, x: number, yy: number, size: number, font = 'F1', color = '0.12 0.18 0.27') => page.push(`BT /${font} ${size} Tf ${color} rg ${x} ${yy} Td (${escPdf(value)}) Tj ET`);
  const rect = (x: number, yy: number, w: number, h: number, color: string) => page.push(`q ${color} rg ${x} ${yy} ${w} ${h} re f Q`);
  const rule = (yy: number, color = '0.80 0.84 0.88') => page.push(`q ${color} RG 0.7 w ${margin} ${yy} m ${pageW - margin} ${yy} l S Q`);
  const finishPage = () => { text('Synthetic demonstration data only  •  Human review required', margin, 24, 7, 'F1', '0.35 0.42 0.5'); text(`Page ${content.length + 1}`, 525, 24, 7, 'F1', '0.35 0.42 0.5'); content.push(page.join('\n')); };
  startPage(); text('PRIOR AUTHORIZATION REQUEST', margin, 724, 20, 'F2', '0.08 0.20 0.31'); text(`Case ${packet.caseId}`, margin, 701, 9.5, 'F1', '0.35 0.42 0.49'); text(`Generated ${new Date().toLocaleDateString('en-US', { timeZone: 'America/Chicago' })}`, margin, 686, 9.5, 'F1', '0.35 0.42 0.49'); const statusText = packet.isDraft ? 'DRAFT / NOT READY' : 'READY FOR REVIEW'; const statusWidth = packet.isDraft ? 112 : 112; rect(pageW - margin - statusWidth, 700, statusWidth, 20, packet.isDraft ? '0.96 0.91 0.79' : '0.85 0.94 0.90'); text(statusText, pageW - margin - statusWidth + 9, 707, 7.5, 'F2', packet.isDraft ? '0.47 0.29 0.05' : '0.08 0.35 0.26'); if (packet.isDraft) text('Unresolved requirements remain', pageW - margin - statusWidth, 684, 7.5, 'F1', '0.47 0.29 0.05'); rule(662, '0.18 0.35 0.48');
  y = 638; const summary = [['CASE ID', packet.caseId], ['STATUS', statusText], ['PAYER', packet.sections[2]?.rows[0]?.[1] ?? 'Not verified'], ['EQUIPMENT', packet.sections[3]?.rows[0]?.[1] ?? 'Not verified']]; text('CASE SUMMARY', margin, y, 8, 'F2', '0.31 0.40 0.48'); y -= 18; summary.forEach(([label, value], index) => { const x = margin + (index % 2) * 252; const yy = y - Math.floor(index / 2) * 35; text(label, x, yy, 7, 'F2', '0.38 0.44 0.50'); wrap(value, 34).forEach((part, line) => text(part, x, yy - 12 - line * 11, 9, 'F1', value === 'Not verified' ? '0.47 0.47 0.47' : '0.08 0.14 0.22')); }); y -= 76;
  for (const section of packet.sections) { if (y < 120) { finishPage(); startPage(); y = 744; } text(section.title, margin, y, 9.5, 'F2', '0.08 0.22 0.38'); y -= 7; rule(y); y -= 22; for (const [label, value] of section.rows) { const wrapped = wrap(value, 48); text(label, margin, y, 8, 'F2', '0.29 0.38 0.48'); wrapped.forEach((part, i) => text(part, margin + 174, y - i * 12, 8.5, 'F1', value === 'Not verified' ? '0.55 0.55 0.55' : '0.1 0.16 0.24')); y -= Math.max(23, wrapped.length * 12 + 9); } y -= 12; }
  if (y < 130) { finishPage(); startPage(); y = 744; } rect(margin, y - 21, pageW - margin * 2, 21, '0.82 0.88 0.94'); text('SUPPORTING DOCUMENTATION', margin + 10, y - 14, 9, 'F2', '0.08 0.22 0.38'); y -= 38; for (const doc of packet.documents) { text('•', margin + 14, y, 9, 'F2', '0.08 0.42 0.4'); text(doc, margin + 28, y, 8.5, 'F1'); y -= 18; }
  text(`Generated ${new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' })}`, margin, 42, 7, 'F1', '0.35 0.42 0.5'); finishPage();
  const objects: string[] = []; const add = (value: string) => { objects.push(value); return objects.length; }; const pages = add('<< /Type /Pages /Kids [] /Count 0 >>'); const regular = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); const bold = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'); const pageIds: number[] = [];
  for (const stream of content) { const length = Buffer.byteLength(stream, 'binary'); const streamId = add(`<< /Length ${length} >>\nstream\n${stream}\nendstream`); pageIds.push(add(`<< /Type /Page /Parent ${pages} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${regular} 0 R /F2 ${bold} 0 R >> >> /Contents ${streamId} 0 R >>`)); }
  objects[pages - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`; const catalog = add(`<< /Type /Catalog /Pages ${pages} 0 R >>`); let out = '%PDF-1.4\n'; const offsets = [0]; for (let i = 0; i < objects.length; i++) { offsets.push(Buffer.byteLength(out, 'binary')); out += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`; } const xref = Buffer.byteLength(out, 'binary'); out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`; return Buffer.from(out, 'binary');
}

function xml(value: string) { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function crc32(buf: Buffer) { let c = 0xffffffff; for (const b of buf) { c ^= b; for (let k = 0; k < 8; k++) c = (c >>> 1) ^ ((c & 1) ? 0xedb88320 : 0); } return (c ^ 0xffffffff) >>> 0; }
export function renderDocx(packet: ExportPacket): Buffer {
  const section = (title: string, rows: Array<[string, string]>) => `<w:p><w:pPr><w:pStyle w:val="Heading2"/><w:spacing w:before="220" w:after="100"/></w:pPr><w:r><w:t>${xml(title)}</w:t></w:r></w:p>${rows.map(([label, value]) => `<w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="2500"/></w:tabs><w:spacing w:after="90"/></w:pPr><w:r><w:rPr><w:b/><w:color w:val="40566D"/></w:rPr><w:t>${xml(label)}</w:t></w:r><w:r><w:tab/><w:t>${xml(value)}</w:t></w:r></w:p>`).join('')}`;
  const body = `<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>PRIOR AUTHORIZATION REQUEST</w:t></w:r></w:p><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>${xml(`Case ${packet.caseId}  |  ${packet.readinessLabel}`)}</w:t></w:r></w:p>${packet.sections.map((s) => section(s.title, s.rows)).join('')}<w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:t>SUPPORTING DOCUMENTATION</w:t></w:r></w:p>${packet.documents.map((d) => `<w:p><w:r><w:t>• ${xml(d)}</w:t></w:r></w:p>`).join('')}<w:p><w:r><w:i/><w:t>Synthetic demonstration data only. Human review required. No coverage or medical-necessity decision is made by the system.</w:t></w:r></w:p>`;
  const files: [string, string][] = [
    ['[Content_Types].xml', '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>'],
    ['_rels/.rels', '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'],
    ['word/_rels/document.xml.rels', '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'],
    ['word/document.xml', `<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900"/></w:sectPr></w:body></w:document>`],
    ['word/styles.xml', '<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="34"/><w:color w:val="163A5C"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="Heading 2"/><w:rPr><w:b/><w:sz w:val="22"/><w:color w:val="163A5C"/></w:rPr></w:style></w:styles>'],
  ];
  const chunks: Buffer[] = []; const central: Buffer[] = []; let offset = 0;
  for (const [name, text] of files) { const data = Buffer.from(text); const n = Buffer.from(name); const h = Buffer.alloc(30); h.writeUInt32LE(0x04034b50, 0); h.writeUInt16LE(20, 4); h.writeUInt32LE(crc32(data), 14); h.writeUInt32LE(data.length, 18); h.writeUInt32LE(data.length, 22); h.writeUInt16LE(n.length, 26); const local = Buffer.concat([h, n, data]); chunks.push(local); const c = Buffer.alloc(46); c.writeUInt32LE(0x02014b50, 0); c.writeUInt16LE(20, 4); c.writeUInt16LE(20, 6); c.writeUInt32LE(crc32(data), 16); c.writeUInt32LE(data.length, 20); c.writeUInt32LE(data.length, 24); c.writeUInt16LE(n.length, 28); c.writeUInt32LE(offset, 42); central.push(Buffer.concat([c, n])); offset += local.length; }
  const cd = Buffer.concat(central); const e = Buffer.alloc(22); e.writeUInt32LE(0x06054b50, 0); e.writeUInt16LE(files.length, 8); e.writeUInt16LE(files.length, 10); e.writeUInt32LE(cd.length, 12); e.writeUInt32LE(offset, 16); return Buffer.concat([...chunks, cd, e]);
}
