import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getDatabase } from '@/db/client';
import { requirePermission } from '@/lib/auth/current-user';
import { updateCommunication, listCommunications } from '@/db/repositories/communications';
import { recordAuditEvent } from '@/db/repositories/audit-events';
import { requestUserHasPermission } from '@/lib/auth/request-authorization';
import { deleteCommunicationDraft } from '@/lib/communications/communication-service';
const schema=z.object({editedContent:z.object({subject:z.string().optional(),body:z.string().min(1),notes:z.array(z.string()).optional()}).nullable().optional(),status:z.enum(['DRAFT','REVIEWED','USED','DISCARDED']).optional()});
export async function PATCH(req:Request,{params}:{params:Promise<{caseId:string;communicationId:string}>}){const user=await requirePermission('cases.write');const {caseId,communicationId}=await params;if(!listCommunications(caseId).some((c)=>c.id===communicationId))return NextResponse.json({error:'Communication not found'},{status:404});const p=schema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:'Invalid request'},{status:400});const row=updateCommunication(communicationId,{...p.data,reviewedByUserId:p.data.status==='REVIEWED'?user.id:undefined});if(!row)return NextResponse.json({error:'Communication not found'},{status:404});recordAuditEvent({userId:user.id,action:`communication.${p.data.status==='REVIEWED'?'reviewed':p.data.status==='DISCARDED'?'discarded':p.data.status==='USED'?'marked_used':'edited'}`,resourceType:'case_communication',resourceId:communicationId});return NextResponse.json({ok:true});}
export async function DELETE(req:NextRequest,{params}:{params:Promise<{caseId:string;communicationId:string}>}){const user=requestUserHasPermission(req,'cases.write')??requestUserHasPermission(req,'communications.generate');if(!user)return NextResponse.json({error:'You do not have permission to delete communication drafts.'},{status:403});const {caseId,communicationId}=await params;const existing=listCommunications(caseId,getDatabase(),true).find((communication)=>communication.id===communicationId);if(!existing)return NextResponse.json({error:'Communication not found'},{status:404});if(!['DRAFT','DISCARDED'].includes(existing.status))return NextResponse.json({error:'Only draft or discarded communications can be deleted.'},{status:409});if(!deleteCommunicationDraft({caseId,communicationId,userId:user.id},getDatabase()))return NextResponse.json({error:'Only draft or discarded communications can be deleted.'},{status:409});return NextResponse.json({ok:true});}
