'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';

type Field = { key: string; label: string; value: string | null; confidence: string; sourceFilename: string | null; needsReview: boolean };

export function NewCaseIntake() {
  const router = useRouter(); const [fields, setFields] = useState<Field[]>([]); const [files, setFiles] = useState<File[]>([]); const [intakeId, setIntakeId] = useState(''); const [warnings, setWarnings] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function readJson(response: Response): Promise<Record<string, unknown>> { const text = await response.text(); if (!text.trim()) return { success: false, error: 'The server returned an empty response.' }; try { return JSON.parse(text) as Record<string, unknown>; } catch { return { success: false, error: 'The server returned an invalid response.' }; } }
  async function analyze() { setBusy(true); setError(''); try { const form = new FormData(); files.forEach((file) => form.append('files', file)); const response = await fetch('/api/cases/intake', { method: 'POST', body: form }); const result = await readJson(response); if (!response.ok || result.success === false) setError(typeof result.error === 'string' ? result.error : 'Unable to analyze the document dump.'); else { setIntakeId(typeof result.intakeId === 'string' ? result.intakeId : ''); setFields((result.fields ?? []) as Field[]); setWarnings(Array.isArray(result.duplicateWarnings) ? result.duplicateWarnings as string[] : []); } } catch { setError('Unable to reach the local application.'); } finally { setBusy(false); } }
  async function create() { setBusy(true); setError(''); try { const response = await fetch('/api/cases/intake', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ intakeId, fields: fields.map((field) => ({ key: field.key, value: field.value })), assignToSelf: true }) }); const result = await readJson(response); if (!response.ok || result.success !== true || typeof result.caseId !== 'string') { setError(typeof result.error === 'string' ? result.error : 'Unable to create the case.'); return; } router.push(`/cases/${result.caseId}`); } catch { setError('Unable to reach the local application.'); } finally { setBusy(false); } }
  return <section className="mt-8 space-y-4 rounded-2xl border border-slate-200 bg-slate-50 p-5"><label className="block rounded-xl border-2 border-dashed border-slate-300 bg-white p-8 text-center"><span className="text-sm font-semibold text-slate-800">Upload synthetic document dump</span><span className="mt-1 block text-xs text-slate-500">TXT files can be analyzed now. PDF and image files are stored for later review.</span><input className="mt-4 block w-full text-sm" type="file" multiple accept=".txt,.pdf,.png,.jpg,.jpeg" onChange={(event) => setFiles(Array.from(event.target.files ?? []))} /></label>{files.length > 0 && <p className="text-sm text-slate-600">{files.length} documents selected.</p>}<Button disabled={!files.length || busy} onClick={() => void analyze()}>Analyze document dump</Button>{warnings.map((warning) => <p key={warning} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{warning}</p>)}{fields.length > 0 && <div className="space-y-3"><h2 className="font-semibold text-slate-900">Review proposed case</h2>{fields.map((field) => <label key={field.key} className="block rounded-xl border border-slate-200 bg-white p-3"><span className="text-xs font-semibold uppercase text-slate-500">{field.label} · {field.confidence}{field.needsReview ? ' · Needs review' : ''}</span><input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={field.value ?? ''} onChange={(event) => setFields((current) => current.map((item) => item.key === field.key ? { ...item, value: event.target.value } : item))} /><span className="mt-1 block text-xs text-slate-500">Source: {field.sourceFilename ?? 'Not found'}</span></label>)}<Button disabled={busy || !intakeId} onClick={() => void create()}>Create case and continue</Button></div>}{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}</section>;
}
